"""update table

Revision ID: 3ff1d6d34fe2
Revises: 21d070d356c1
Create Date: 2023-11-28 18:55:40.393879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff1d6d34fe2'
down_revision: Union[str, None] = '21d070d356c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_card', sa.Column('card_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_card', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_card', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_card', type_='foreignkey')
    op.drop_constraint(None, 'user_card', type_='foreignkey')
    op.drop_column('user_card', 'card_id')
    op.drop_column('user_card', 'user_id')
    # ### end Alembic commands ###
